# Generated by Django 4.1.3 on 2022-12-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('difficulty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mountaineering_Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('height', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=100)),
                ('descripton', models.TextField()),
                ('hut', models.BooleanField()),
                ('image', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.ManyToManyField(related_name='mountaineering_routes', to='difficulty.difficulty')),
            ],
        ),
    ]
