# Generated by Django 4.1.4 on 2022-12-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountaineering_routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountaineering_route',
            name='image',
        ),
    ]
