# Generated by Django 4.1.4 on 2022-12-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountaineering_routes', '0002_remove_mountaineering_route_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountaineering_route',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
