# Generated by Django 4.1.4 on 2022-12-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_comment_image1_comment_image2_comment_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='image3',
        ),
    ]
