# Generated by Django 4.1.4 on 2022-12-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_remove_comment_image2_remove_comment_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image2',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='image3',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
